const loader=document.getElementById("loader");window.addEventListener("load",()=>setTimeout(()=>loader.classList.add("done"),850));const nav=document.getElementById("siteNav"),menu=document.getElementById("menuToggle");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open);});document.querySelectorAll(".nav-link").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");menu.setAttribute("aria-expanded","false");}));const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible");}),{threshold:.1});document.querySelectorAll(".reveal").forEach(el=>revealObserver.observe(el));const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;document.querySelectorAll(".nav-link").forEach(a=>a.classList.remove("active"));const a=document.querySelector('.nav-link[href="#'+e.target.id+'"]');if(a)a.classList.add("active");}),{rootMargin:"-35% 0px -55% 0px"});document.querySelectorAll("main section[id]").forEach(s=>navObserver.observe(s));const glow=document.getElementById("cursorGlow");window.addEventListener("pointermove",e=>{if(glow){glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px";}});if(window.matchMedia("(pointer:fine)").matches){document.querySelectorAll("[data-tilt]").forEach(card=>{card.addEventListener("pointermove",e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform="perspective(1000px) rotateX("+(-y*5)+"deg) rotateY("+(x*7)+"deg) translateZ(8px)";});card.addEventListener("pointerleave",()=>card.style.transform="");});}document.getElementById("year").textContent=new Date().getFullYear();
/* RAISEN OS — PHASE 1 INTERACTIONS */
(()=>{
 const boot=document.getElementById("osBoot"), progress=document.getElementById("bootProgress"), status=document.getElementById("bootStatus"), log=document.getElementById("bootLog"), skip=document.getElementById("bootSkip");
 const lines=["LOADING IDENTITY MATRIX...","MOUNTING PROJECT DATABASE...","SYNCING SKILL MODULES...","CALIBRATING CURIOSITY ENGINE...","RAISEN CORE ONLINE."];
 let i=0, timer;
 const finish=()=>{clearInterval(timer);progress.style.width="100%";status.textContent="SYSTEM ONLINE";log.textContent="WELCOME, ARYAN.";setTimeout(()=>boot.classList.add("done"),450);sessionStorage.setItem("raisenBooted","1");};
 if(sessionStorage.getItem("raisenBooted")==="1"){boot.classList.add("done");}else{
  timer=setInterval(()=>{i++;progress.style.width=Math.min(i*20,100)+"%";status.textContent=lines[Math.min(i-1,lines.length-1)];log.textContent=lines[Math.min(i-1,lines.length-1)];if(i>=5)finish();},420);
 }
 skip.addEventListener("click",finish);
})();
(()=>{
 const overlay=document.getElementById("osLauncher"), openBtn=document.getElementById("osCommandButton"), closeBtn=document.getElementById("launcherClose"), input=document.getElementById("commandInput"), output=document.getElementById("commandOutput");
 const commands={help:"Available: about • skills • projects • journey • contact • github • home • clear",about:"Aryan Kumar — 2nd year CSE (AI & ML) student, builder and explorer.",skills:"C • C++ • Python • DSA • AI/ML → Generative AI",projects:"Raisen Portfolio • Tic-Tac-Toe • LeetCode / DSA practice",journey:"C → DSA → Python → ML → Generative AI",contact:"Scroll to the contact section or use the social links.",github:"Opening GitHub...",home:"Returning to the core..."};
 const run=(raw)=>{const c=raw.trim().toLowerCase();if(!c)return;if(c==="clear"){output.innerHTML="";return}if(c==="github"){output.textContent="Opening GitHub...";setTimeout(()=>window.open("https://github.com/Aryan24022007","_blank"),250);return}if(c==="home"){location.hash="home";close();return}if(["about","skills","projects","journey","contact"].includes(c)){output.textContent=commands[c];location.hash=c;return}output.innerHTML=commands[c]?commands[c]:"Command not found. Type <b>help</b>.";};
 const open=()=>{overlay.classList.add("open");overlay.setAttribute("aria-hidden","false");setTimeout(()=>input.focus(),100)};
 const close=()=>{overlay.classList.remove("open");overlay.setAttribute("aria-hidden","true");input.value=""};
 openBtn.addEventListener("click",open);closeBtn.addEventListener("click",close);overlay.addEventListener("click",e=>{if(e.target===overlay)close()});input.addEventListener("keydown",e=>{if(e.key==="Enter")run(input.value);if(e.key==="Escape")close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&overlay.classList.contains("open"))close();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();open()}});
 document.querySelectorAll(".launcher-hints button").forEach(b=>b.addEventListener("click",()=>run(b.dataset.command)));
})();
